name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  VCPKG_BINARY_SOURCES: "default;http,https://scivis-vcpkg-cache.it.liu.se/cache/{sha},readwrite,Authorization: Bearer ${{ secrets.VCPKG_CACHE_TOKEN }}"

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux (GCC)
            os: ubuntu-latest
            preset: ninja-developer
          - name: Windows (MSVC)
            os: windows-latest
            preset: msvc-developer
          - name: macOS (Xcode)
            os: macos-latest
            preset: xcode-developer-arm64

    steps:
      - name: "Clone Vcpkg Cache Server"
        uses: actions/checkout@v6
        with:
          path: vcpkg-cache-server
          
      - name: "Get Vcpkg SHA"
        shell: bash
        run: |
          SHA=`jq -r '.["vcpkg-configuration"].["default-registry"].baseline' vcpkg-cache-server/vcpkg.json`
          echo "VCPKG_SHA=${SHA}" >> $GITHUB_ENV

      - name: "Clone Vcpkg"
        uses: actions/checkout@v6
        with:
          repository: microsoft/vcpkg
          ref: ${{ env.VCPKG_SHA }}
          fetch-depth: 0
          path: vcpkg

      - name: "VCPKG Update"
        shell: bash
        run: |
          cd vcpkg
          ./bootstrap-vcpkg.sh
          echo "VCPKG_INSTALLATION_ROOT=`pwd`" >> $GITHUB_ENV
          echo "VCPKG_ROOT=`pwd`" >> $GITHUB_ENV
    
      - name: Configure
        run: cmake -S vcpkg-cache-server --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build builds/vcpkg-cache-server-${{ matrix.preset }} --parallel
